axios,react-queryの追加,
ryogosteeny/agile-project-management pull request #10
Opened 2021-11-16 13:28 UTC by ryogosteeny

# 概要
axios及びreact-queryの追加、設定

# 詳細

# スクリーンショット
 （※ コンポーネントの追加、UIの変更を行なった時)

2021-11-17 14:00 UTC, ryo-wens requested changes

2021-11-17 14:08 UTC, ryogosteeny commented
b4d1882

src/hooks/api/axiosConfig.tsの修正

- baseURLの余白の修正

2021-11-17 14:25 UTC, ryo-wens approved these changes

2021-11-17 14:25 UTC, ryo-wens commented on src/providers/QueryProvider.tsx
> +  });
ここに改行を入れてほしいです。

2021-11-17 14:33 UTC, ryogosteeny commented
7217b7f

src/providers/QueryProvider.tsx修正

- return部分改行の追加

2021-11-17 14:33 UTC, ryo-wens approved these changes

2021-11-18 13:50 UTC, ryo-wens commented on src/hooks/api/axiosConfig.ts
> +  baseURL: process.env['REACT_APP_API_BASEURL'],
`process.env.REACT_APP_API_BASEURL`にしましょう。

2021-11-18 14:10 UTC, ryogosteeny commented
e58d4d0

- .env.developmentのbaseURLの配列削除
- src/components/icons/MenuIcon.tsxの`styleTheme`のpath修正

2021-11-18 14:13 UTC, ryo-wens approved these changes

2021-11-20 08:53 UTC, ryogosteeny commented
1c60713

themeディレクトリのファイルの切り分けによる相対パスのわかりずらさと違和感の解消
- src/providers/theme/StyleThemeProvider.tsx → src/providers/StyleThemeProvider.tsx
- src/providers/theme/theme.ts → src/theme/theme.ts

2021-11-20 14:11 UTC, ryo-wens submitted a review, later dismissed

2021-11-21 05:39 UTC, ryogosteeny commented
48ba242

- src/hooks/api/axiosConfig.ts → src/axiosInstance.tsへのリネーム

2021-11-21 06:39 UTC, ryo-wens approved these changes

2021-11-21 06:44 UTC, merged