プロジェクト一覧取得のエンドポインのトカスタムフックの作成
ryogosteeny/agile-project-management pull request #13
Opened 2021-12-01 04:00 UTC by ryogosteeny

# 概要

- `useQueryWrapper.ts,useFetchProjects.ts`のカスタムフック作成
-  `useFetchProjects.test.tsx`のテスト作成
-  `fetchProjectsResponse.json`のモックデータ作成
-  `axiosInstance.ts`へのinterceptors処理追加
-  `types.ts`の作成

# 詳細

プロジェクト一覧取得のエンドポイントの為の`useFetchProjects.ts`を作成しました。それに基づきuseQueryでの共通の処理を目的とした、`useQueryWrapper.ts`の作成実施しました。(エラー処理に関しては共通のエラーハンドリングがまだ未定な為保留)

`useQueryWrapper.ts,useFetchProjects.ts`のテスト`useFetchProjects.test.tsx`作成、axiosのモックの為、
axios-mock-adapterのライブラリー追加。
モックデータ`fetchProjectsResponse.json`の作成実施しました。

`useQueryWrapper.ts`の処理実現とエラーコード500のみのエラー処理をここで実現させる為、axiosInstance.ts`へのinterceptors処理追加(ここも共通のエラーハンドリング未定な為保留)

`types.ts`ではエンドポイント毎の型を切り出し、管理を目的としてコメントアウトで機能毎にグループ分けを実施しようと考えてます。
また`useFetchProjects.ts`で使用している`TUseQueryOptions`は汎用的な為切り出し実施しました。

レビューの方よろしくお願いいたします！

2021-12-01 14:54 UTC, ryo-wens requested changes
何点かコメントしました。
改行を意識して入れていくとコードが読みやすくなると思います。

2021-12-01 14:54 UTC, ryo-wens commented on src/hooks/api/useFetchProjects.test.tsx
> +  const MockAdapter = require('axios-mock-adapter');
ここも改行を入れましょう。

2021-12-01 15:55 UTC, ryogosteeny commented
a859694

- src/hooks/api/types.tsのtypeをinterfaceへ修正
- src/hooks/api/useFetchProjects.test.tsxの改行実施
- .storybook/preview.jsのパス指定の修正

2021-12-03 19:21 UTC, toshi1127 commented on src/axiosInstance.ts
> +      // TODO エラーハンドリングを書く
ここでハンドリングした結果をどうする想定ですか？？またいつ実装する感じでしょう？

2021-12-03 19:21 UTC, toshi1127 commented on src/hooks/api/useFetchProjects.test.tsx
> +describe('useFetchProjects,useQueryWrapperのテスト', () => {
useFetchProjects,useQueryWrapperのテストとありますが、useQueryWrapperのテストはどこにありますか？

2021-12-03 19:21 UTC, toshi1127 commented on src/hooks/api/useFetchProjects.test.tsx
> +  test('useFetchProjectsのレスポンスデータのテスト', async () => {
いまいちこのテストを書くうまみがわからず.....
useQueryWrapperをラップしているだけなので、useQueryWrapperのテストだけ書けば十分だったりして....

2021-12-04 04:06 UTC, ryogosteeny commented on src/axiosInstance.ts
> +      // TODO エラーハンドリングを書く
現在のところ`axiosInstance.tsとusecQueryWrapper.tsx`ではエラーを投げ、ErrorBundary等のライブラリーを使用してコンポーネント側でエラー検知をして、`axiosInstance.ts`では500のエラーメッセージと`useQueryWrapper.tsx`ではエラー状況に合わせたエラーメッセージをダイアログコンポーネントなりページなりに表示をさせたいと思っており、
いずれも表示のコンポーネントを作成した際に実装したいと考えております。

2021-12-04 04:27 UTC, ryogosteeny commented on src/hooks/api/useFetchProjects.test.tsx
> +describe('useFetchProjects,useQueryWrapperのテスト', () => {
言葉足らずで申し訳ございません。
`useFetchProjects.tsx`ではtoshizoさんが下記に書いていただいたようにuseQueryWrapperをラップしているだけのものでしたので
`useFetchProjects.tsx`と`useQueryWrapper.tsx`を一緒にまとめてテストしてしまおうという考えでテストファイルを
一つに絞って書きました。
`useFetchProjects,useQueryWrapperのテスト`では分かりづらいですねすいません💦

2021-12-04 04:30 UTC, ryogosteeny commented on src/hooks/api/useFetchProjects.test.tsx
> +  test('useFetchProjectsのレスポンスデータのテスト', async () => {
上記の理由にしろ、useQueryWrapperだけのテストだけで十分でしょうか?

2021-12-05 16:39 UTC, ryogosteeny commented
1f4c54f

- `src/hooks/api/useFetchProjects.test.tsx`→`src/hooks/api/useQueryWrapper.test.tsx` へのリネーム

2021-12-06 15:20 UTC, toshi1127 commented on src/axiosInstance.ts
> +      // TODO エラーハンドリングを書く
> (表示の仕方はまだ明確に決まっておらず)に表示をさせたいと思っており、
いずれも表示のコンポーネントを作成した際に実装したいと考えております。

この状況でinterceptorとか、usecQueryWrapperで横断的にエラーのハンドリングを検知する方向に倒した背景が気になりますね

2021-12-10 09:38 UTC, ryogosteeny commented
ca37a8c

- src/axiosInstance.tsの修正
今回はステータスコード500のページを作成する仕様に決定した為、共通の処理として500の場合、
ページ遷移する処理をページが出来上がり次第記述していこうと思っております。
- src/hooks/api/useFetchProjects.test.tsxの修正
- src/hooks/api/useQueryWrapper.tsの削除
- src/hooks/api/useFetchProjects.tsの修正

2021-12-13 15:51 UTC, ryo-wens reviewed
1点コメントしました。

2021-12-13 15:51 UTC, ryo-wens commented on src/hooks/api/useFetchProjects.ts
> +export const useFetchProjects = () => {
fetchが失敗してerrorになった場合は、どうエラーハンドリングをしますか？

2021-12-13 16:07 UTC, ryogosteeny commented on src/hooks/api/useFetchProjects.ts
> +export const useFetchProjects = () => {
エラーハンドリングについては呼び出し側のコンポーネントの方でisError等のステータスを受け取り、エラー表示方法に合わせたメッセージ等適切な処理を下記の記事のように実装したいと思っています。
必要なタイミングで実装したいと思っております。

https://tkdodo.eu/blog/react-query-error-handling#:~:text=The%20standard%20example

2021-12-13 16:33 UTC, ryo-wens commented on src/hooks/api/useFetchProjects.ts
> +export const useFetchProjects = () => {
今回の修正のように当初の実装と大きく異なる際は、実装の意図をコメントに書くようにするとレビューしやすくなるので、意識してみるといいと思います。

2021-12-13 16:33 UTC, ryo-wens approved these changes

2021-12-15 15:23 UTC, ryogosteeny commented
a371823

- `src/hooks/api/useFetchProjects.ts` → `src/api/fetchProjects.ts`へ修正
- `src/hooks/api/useFetchProjects.test.tsx` → `src/api/fetchProjects.test.ts`へ修正
- `src/hooks/api/types.ts` → `src/api/types.ts`にrename

2021-12-15 15:38 UTC, ryo-wens approved these changes

2021-12-27 05:35 UTC, ryogosteeny commented
244ff98

- src/api/fetchProjects.test.tsの削除
fetchProjects.tsの仕様(呼び出しの関数)をかみして検討したところ、ここのレイヤーでテストをする意味がないと判断した為、
testとmockの為に用意していたデータファイルは削除します。

2021-12-27 06:02 UTC, ryogosteeny commented
39561b4

- fetchProjects.tsの戻り値の型の修正

2021-12-27 08:24 UTC, ryo-wens submitted a review, later dismissed

2021-12-28 04:21 UTC, ryogosteeny commented
ea17497
- src/api/types.tsの型修正
- axios-mock-adapterの削除

2022-01-04 07:50 UTC, ryogosteeny commented
d43a7c6

- 意図しないアップデート、今後の共同開発メンバーとのバージョン差異を防ぐ為、package.jsonのバージョン固定の実施
- 新規のパッケージのインストール時のバージョン固定のため`.npmrc`の追加

2022-01-04 14:13 UTC, toshi1127 approved these changes

2022-01-04 23:55 UTC, ryo-wens approved these changes

2022-01-05 06:23 UTC, merged