Cardコンポーネントを追加
ryogosteeny/agile-project-management pull request #14
Opened 2021-12-25 10:55 UTC by akari97

# やったこと

- `Crad.tsx`の作成
- `Card.stories.tsx`の作成

# やらないこと

なし

# スクリーンショット

<img width="256" alt="スクリーンショット 2021-12-25 19 46 06" src="https://user-images.githubusercontent.com/88522007/147383375-4eab436b-6b32-404d-936d-6c6b19cc7ddf.png">

# その他

- 文字数が長い場合、末尾に`...`をつけようと思っているのですが、Card.tsxでは、propsで受け取った値を表示させるのみ行い、文字列の加工処理については、親コンポーネントで行う形にしたいと思います。

2021-12-26 04:36 UTC, ryogosteeny requested changes

2021-12-26 04:36 UTC, ryogosteeny commented on src/components/atoms/Card.stories.tsx
> +};
chromaticでのstoryの公開はしないのでしょうか？

https://www.chromatic.com/docs/

2022-01-04 06:14 UTC, akari97 commented on src/components/atoms/Card.stories.tsx
> +};
> chromaticでのstoryの公開はしないのでしょうか？
> 
> https://www.chromatic.com/docs/

@ryogosteeny 
url添付しました。確認お願いします。

2022-01-06 02:42 UTC, ryogosteeny submitted a review, later dismissed

2022-01-07 11:54 UTC, toshi1127 reviewed
.DS_Storeは.gitiignoreの追加しておくのが無難かなと！

2022-01-07 11:55 UTC, toshi1127 commented on src/components/atoms/Card.stories.tsx
> +  title: 'Card',
atomis/Cardみたいにした方が、フォルダになってみやすいかな

2022-01-07 11:56 UTC, toshi1127 commented on src/components/atoms/Card.stories.tsx
> +      <Card projectData={[]} projectColor={''} title={''} onClick={() => {}} {...args} />
argsに型当たっていれば、projectData={[]} projectColor={''} title={''} onClick={() => {}}は要らない気がします

2022-01-07 11:56 UTC, toshi1127 commented on src/components/atoms/Card.tsx
> +`;
最後って改行入れない設定なんでしたっけ？

2022-01-11 08:45 UTC, akari97 commented on src/components/atoms/Card.tsx
> +`;
エディターの最後の行に改行を入れる設定がされていなかったので、設定しました。

2022-01-16 12:40 UTC, akari97 commented
@toshi1127 
8e6c626
ご指摘いただいた箇所の修正完了しました。確認よろしくお願いいたします。

2022-01-17 04:59 UTC, ryogosteeny submitted a review, later dismissed

2022-01-22 10:45 UTC, akari97 commented
@toshi1127 
059e0af99bae26bc14eb0d7ec3a9872b0335ae97
ご指摘いただいた箇所の修正完了しました。確認よろしくお願いいたします。

2022-01-24 06:24 UTC, ryogosteeny submitted a review, later dismissed

2022-01-24 13:51 UTC, akari97 commented
@toshi1127 
6ca257097582cfe3e47a65143a84ade4d44d872c
.DS_Storeの削除完了しました。ご確認よろしくお願いいたします。

2022-01-24 14:15 UTC, toshi1127 approved these changes

2022-01-25 05:29 UTC, merged