プロジェクト編集ページviewの作成
ryogosteeny/agile-project-management pull request #16
Opened 2022-01-20 17:23 UTC by ryogosteeny

# やったこと

- プロジェクト編集ページのview部分の作成
ページの全体的な構成の把握の目的の為、ページview部分のみ作成しました。

- 使用コンポーネントの修正
ページレイアウト時にデザイン仕様に満てなかった為、修正実施してます。

- mediaQueryの設定
ブレイクポイント設定は
タブレット対応の為max-width 1024px、モバイルを想定でのmax-width768pxに設定しました。

# やらないこと

- 編集ページのバリデーション実装
以下の実装後に実施します。

- ページ遷移の関数実装
routerの設定後に実施します。

- API関数の設置
APIの関数作成後実施します。

- ローカル、グローバルナビの実装
コンポーネント作成後に実装実施します。

# スクリーンショット

<img width="468" alt="スクリーンショット 2022-01-17 17 05 52" src="https://user-images.githubusercontent.com/77338175/150388685-2df03a6b-08b9-4c0a-8ca3-181196ef9975.png">
<img width="459" alt="スクリーンショット 2022-01-17 17 06 29" src="https://user-images.githubusercontent.com/77338175/150388696-9b826d6a-1524-45bc-ad41-fe5ad2594810.png">
<img width="1792" alt="スクリーンショット 2022-01-17 17 06 42（2）" src="https://user-images.githubusercontent.com/77338175/150388701-30aa68b9-32fb-4516-8692-6e0741728e5e.png">

＃ その他

タブレットの縦版でのfooterにローカルナビ配置するかは検討中の為、仮で下に設置しております。

2022-01-20 17:52 UTC, ryogosteeny commented
909e442

- ブレイクポイントの数値間違いの為、修正実施。

2022-01-23 07:21 UTC, ryo-wens reviewed
何点かコメントしました。

2022-01-23 15:42 UTC, neetzama requested changes

2022-01-23 15:42 UTC, neetzama commented on src/pages/project/ProjectEdit.tsx
> +  ${mediaQuery[0]} {
インデックス指定はどのサイズを呼び出しているかイメージしづらいです。[breakPoint](https://github.com/ryogosteeny/agile-project-management/pull/16/files#diff-e62d3d019d66da5284e5cb5c94027a669b7ec95b9ba06e3da645d9e3717254a2R10)とサイズ名を一緒に定義した方が呼び出す際にサイズをイメージしやすいと思います。

2022-01-24 14:05 UTC, ryo-wens commented on src/pages/project/ProjectEdit.tsx
> +  font-size: 2.4rem;
このフォントサイズは、`theme.ts`に追加して使用するとよいと思います。

2022-01-30 12:18 UTC, ryogosteeny commented
materialUIの採用に伴い、スタイル等変更ありの為、クローズします。

2022-01-30 12:18 UTC, closed without merging