PullDownButtonコンポーネントの作成
ryogosteeny/agile-project-management pull request #9
Opened 2021-10-29 08:18 UTC by ryogosteeny

# 概要

- `PullDownButton.tsx`,`PullDownButton.stories.tsx`の作成
- `react-icons`ライブラリーの追加

# 詳細

PullDownButtonコンポーネントの作成を行いました。
仕様としては

- onClickでのプルダウンメニュー表示
- 項目としては、配列の中のオブジェクトでlabelとonClickを渡し、ページ遷移やモーダルの表示等を実現しようと考えています。

ロゴはこれから先々必要だと感じた為、`react-icons`追加し使用しました。

レビューよろしくお願いいたします。

chromatic URL
https://www.chromatic.com/component?appId=6154204cdbe557003a8a55e2&name=PullDownButton&buildNumber=6&componentInspectorKey=617baa2be2c8d7003a0011dc-1200-interactive-true&historyLengthAtIndex=7&distanceToMoveBack=-1

# スクリーンショット
  
<img width="178" alt="スクリーンショット 2021-10-29 17 00 31" src="https://user-images.githubusercontent.com/77338175/139400367-351df873-fc9b-4b20-bf06-2b709ad154c5.png">

2021-10-30 06:36 UTC, ryo-wens requested changes

2021-10-30 06:36 UTC, ryo-wens commented on src/components/PullDownButton.tsx
> +interface ButtonMenuContentsType {
この型は、再利用することになると思うので型定義ファイルを作成して切り出した方がよいと思います。

2021-10-30 06:36 UTC, ryo-wens commented on src/components/PullDownButton.tsx
> +          })}
下記の方がシンプルかと思います。

```
{menuContents.map((menuItem) => (
              <li key={menuItem.label} css={pullDownButtonItemStyle} onClick={menuItem.onClick}>
                <span>{menuItem.label}</span>
              </li>
            ))}
```

2021-10-30 06:36 UTC, ryo-wens commented on src/components/PullDownButton.tsx
> +  box-shadow: 2px 3px 4px gainsboro;
`box-shadow`も再利用することが多いともうので、`styleTheme`に切り出すとよいと思います。

2021-10-30 08:15 UTC, ryogosteeny commented on src/components/PullDownButton.tsx
> +interface ButtonMenuContentsType {
今回のメインとしてはコンポーネントの作成という意図でしたので、
型定義ファイルの作成は次回PRにて行いたいと考えております。
ですので今回は型定義ファイルの修正は見送らせていただきたいです。

2021-10-30 09:37 UTC, ryogosteeny commented
PullDownButton.tsxの修正、theme.tsの変更    0ece55d

- `PullDownButton.tsx`の`menuContents.map`処理のreturn部分の修正
- box-shadowスタイルは、汎用的に使用することを考え、theme.tsへの定義実施及び変更

2021-10-30 13:37 UTC, ryo-wens approved these changes

2021-10-30 13:54 UTC, ryo-wens requested changes

2021-10-30 13:54 UTC, ryo-wens commented on src/components/PullDownButton.tsx
> +  margin: ${styleTheme.spacing(0.5)}px 0 0;
ここは、`margin-top`でいいと思います。

2021-10-30 13:59 UTC, ryogosteeny commented
PullDownButton.tsxのmaginのスタイル変更  6ed113d

- PullDownButton.tsxの`pullDownButtonStyle`を`margin`→`magin-top`へ修正

2021-10-30 14:00 UTC, ryo-wens approved these changes

2021-10-30 23:54 UTC, toshi1127 commented on src/components/PullDownButton.tsx
> +const PullDownButton = forwardRef<HTMLDivElement, Props>(({ onClick, isOpen, menuContents }: Props, ref) => {
https://chakra-ui.com/docs/overlay/menu

これは普通にmenuとかでもいいような
ボタンとして機能するコンポーネントというよりは、削除編集みたいなナビゲーションを示すコンポーネントなのかなと

2021-10-30 23:57 UTC, toshi1127 commented on package.json
> +    "react-icons": "^4.3.1",
figma書いているのであれば、アイコンはそこから書き出してもいいかもですね
(このロゴないとか無くはなさそうですし)

2021-10-30 23:57 UTC, toshi1127 commented on src/components/PullDownButton.tsx
> +    <div css={pullDownButtonContainer} ref={ref}>
親からref使えるようにしているのって何故なんでしたっけ？

2021-10-31 06:08 UTC, ryogosteeny commented on src/components/PullDownButton.tsx
> +    <div css={pullDownButtonContainer} ref={ref}>
@toshi1127 
今回refを使ってやりたかった事としては、範囲外クリックでした。
メニュー外をクリックした場合、閉じることを目的として使用したかった為、
親側でuseRefを定義し管理したかったので、
コンポーネント側でforwardrefでdiv要素の取得をしようと考えていました。

このコンポーネントを作成するにあたって参考にした記事はこちらでした。
https://qiita.com/G4RDSjp/items/58364a6655d4968a90d9

2021-10-31 08:08 UTC, ryogosteeny commented on package.json
> +    "react-icons": "^4.3.1",
@toshi1127 
figmaでアイコンをsvgでエクスポートで書き出して使用するという認識で良いのでしょうか？
また、figmaで書き出して使用する場合、考えているのが`svg to jsx`というfigmaのプラグインで、
SVGコードをreactコンポーネントとしてコピーできるものがあり、それを使用していこうかと考えているのですが
その他にどんなやり方があるのか、ぜひアドバイスいただきたいです。

https://www.figma.com/community/plugin/749818562498396194/SVG-to-JSX

2021-10-31 14:42 UTC, ryogosteeny commented on src/components/PullDownButton.tsx
> +const PullDownButton = forwardRef<HTMLDivElement, Props>(({ onClick, isOpen, menuContents }: Props, ref) => {
OperationMenuというのはどうでしょうか？

(Operation = 操作) + (Menu = 項目)

2021-11-05 05:30 UTC, ryogosteeny commented
PullDownButton修正と変更  40f1028

- `PullDownButton.tsx``PullDownButton.stories.tsx`　→　`Menu.tsx``Menu.stories.tsx`に変更
- figmaでアイコン書き出し`MenuIcon.tsx`作成実施
- カスタムフック`useOpen.tsx`作成

2021-11-06 11:17 UTC, ryo-wens commented on src/components/icons/MenuIcon.tsx
> +    <svg width={size || 24} height={size || 24} fill={color} viewBox="0 0 32 8" xmlns="http://www.w3.org/2000/svg">
fillのcolorは、`styleTheme.colors.text.dark`を指定するケースが多いと思うので、widthとheight同様に
`fill={color || styleTheme.colors.text.dark}`のような形にしてよいと思います。

2021-11-06 11:17 UTC, ryo-wens commented on src/components/icons/MenuIcon.tsx
> +  color: string;
fillのデフォルトカラーに使用頻度の高いカラーを設定することで、ここをオプショナルにすることができ、毎回propsを渡す必要がなくなると思います。

2021-11-06 11:17 UTC, ryo-wens commented on src/components/Menu.tsx
> +  color: string;
`MenuIcon`のcolorをオプショナルにすると、`Menu`では、colorを受け取る必要がなくなると思います。

2021-11-06 13:04 UTC, ryogosteeny commented
MenuIcon.tsxの修正 26e88df    Menu.tsxの修正 4d3414f    Menu.stories.tsxの修正   e29a058

- `MenuIcon.tsx`のfillに`style.theme.text.dark`へ追加、デフォルトスタイルへ設定
- `Menu.tsx`の`MenuIcon`propsデフォルトでのスタイルで補える為、削除
- `Menu.tsx`interface`color,size`削除
- Menu.stories.tsx `color,size`部分削除

2021-11-06 13:06 UTC, ryo-wens approved these changes

2021-11-06 23:02 UTC, toshi1127 approved these changes

2021-11-07 03:43 UTC, merged